# Generated by Django 4.2.3 on 2023-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
