# Generated by Django 4.2.3 on 2023-07-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_participant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participant',
            new_name='participants',
        ),
    ]
